<a href="https://colab.research.google.com/github/saraalmazroa/-IT326-DataMining-Project-/blob/main/Phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Phase 1: Data Selection
## German Credit Risk Dataset

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/saraalmazroa/-IT326-DataMining-Project-/main/Dataset/Raw_dataset.csv"
df = pd.read_csv(url)
df.head()

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1

## Dataset Description

In [ ]:
print(f"Number of attributes: {df.shape[1] - 1}")
df.dtypes

Number of attributes: 20

laufkont    int64
laufzeit    int64
moral       int64
verw        int64
hoehe       int64
sparkont    int64
beszeit     int64
rate        int64
famges      int64
buerge      int64
wohnzeit    int64
verm        int64
alter       int64
weitkred    int64
wohn        int64
bishkred    int64
beruf       int64
pers        int64
telef       int64
gastarb     int64
kredit      int64
dtype: object

In [ ]:
print(f"Number of instances: {df.shape[0]}")

Number of instances: 1000

In [ ]:
target_col = "kredit"
print(f"Class values: {df[target_col].unique()}")   # 1 = good, 0 = bad
print(df[target_col].value_counts())

Class values: [1 0]
kredit
1    700
0    300
Name: count, dtype: int64

In [ ]:
df.sample(5, random_state=42)

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
521,4,36,2,2,10974,1,1,4,2,1,...,3,26,3,2,2,4,2,2,2,0
737,4,18,4,3,1149,4,3,4,3,1,...,1,46,3,2,2,3,2,1,2,1
740,4,12,2,2,1736,1,4,3,2,1,...,1,31,3,2,1,2,2,1,2,1
660,2,8,2,3,1414,1,3,4,3,3,...,1,33,3,2,1,3,2,1,1,1
411,4,24,3,9,2978,5,3,4,3,1,...,1,32,3,2,2,3,1,2,2,1